<a href="https://colab.research.google.com/github/KrishnaBalaSai/Python_Course_Work/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print("1-dim",arr1,sep='\n',end='\n\n')

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2-dim",arr2,sep='\n',end='\n\n')

arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3-dim",arr3,sep='\n',end='\n\n')

1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]

3-dim
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



In [ ]:
zeros = np.zeros((3, 4))
print("zeros_5:", zeros)

ones = np.ones((3, 4))
print("zeros_7:", ones)

identity = np.eye(4)
print(identity)

fullarray = np.full((10, 2), 20)
print(fullarray)

zeros_5: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros_7: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]]


In [ ]:
range_arr = np.arange(10, 0, -1)
print(range_arr)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
range_arr = np.arange(2,51,2)
print(range_arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [ ]:
lin_space = np.linspace(0, 10, 5)
print(lin_space)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
lin_space = np.linspace(0, 100, 5)
print(lin_space)

[  0.  25.  50.  75. 100.]


In [ ]:
rand_arr = np.random.randint(100)
print(rand_arr)

37


In [ ]:
np.random.seed(40)
rand_arr = np.random.randint(100)
print(rand_arr)

70


In [ ]:
rand_float = np.random.rand()
print(rand_float)

0.6440082047534439


In [ ]:
rand_float = np.random.rand(4)
print(rand_float)

[0.11217074 0.7050303  0.14504616 0.58621355]


In [ ]:
rand_int = np.random.randint(1, 6, (4, 3))
print(rand_int)

[[4 3 4]
 [4 4 2]
 [1 2 2]
 [1 5 5]]


In [ ]:
rand_int = np.random.randint(1, 6, 8)
print(rand_int)

[4 5 3 3 3 4 5 5]


In [ ]:
lang = ['html','css','javascript','python','mysql']
rand_choice = np.random.choice(lang, 3)
print(rand_choice)

['javascript' 'javascript' 'javascript']


In [ ]:
arr = np.array([[1, 2],[4, 5],[6, 7],[8, 7],[1, 2],[4, 5]])
print(arr.shape)

(6, 2)


In [ ]:
reshaped = arr.reshape(3,4)
print(reshaped)

[[1 2 4 5]
 [6 7 8 7]
 [1 2 4 5]]


In [ ]:
a = np.array([[1,2,3,4],[1,2,3,4]])
flattened = a.flatten()
print(flattened)

[1 2 3 4 1 2 3 4]


In [ ]:
transposed = arr.T
print(transposed)

[[1 4 6 8 1 4]
 [2 5 7 7 2 5]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60],[70, 80, 90]])
print(matrix[0:3, 1])
print(matrix[1:3, 2])
print(matrix[0:2, 0:2])
print(matrix[1:3,1:3])

[20 50 80]
[60 90]
[[10 20]
 [40 50]]
[[50 60]
 [80 90]]


In [ ]:
arr = np.array([4, 9, 16, 25, 36])

In [ ]:
print(arr+10)
print(arr*2)
print(arr**0.5)

[14 19 26 35 46]
[ 8 18 32 50 72]
[2. 3. 4. 5. 6.]


In [ ]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

90
18.0
16.0


In [ ]:
a = np.array([1,2,3,4,5])
print(np.mean(a))
print(np.var(a))
print(np.std(a))

3.0
2.0
1.4142135623730951


In [ ]:
print(np.min(arr))
print(np.max(arr))

4
36


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [ ]:
arr = np.array([1,2,3,4,5,5,6,6,7,8,8,3])
print(arr%2==0)
print(arr[arr%2!=0])

[False  True False  True False False  True  True False  True  True False]
[1 3 5 5 7 3]


In [ ]:
arr = np.array([3,1,4,5,9,2,6])
sorted_array = np.sort(arr)
print(sorted_array)

[1 2 3 4 5 6 9]


In [ ]:
unique_vals = np.unique(arr)
print(unique_vals)

[1 2 3 4 5 6 9]


In [ ]:
arr = np.array([10,20,30])
view_arr = arr.view()
view_arr[0] = 100
print(arr, view_arr)

copy_arr = arr.copy()
copy_arr[0] =200
print(arr, copy_arr)

[100  20  30] [100  20  30]
[100  20  30] [200  20  30]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [ ]:
print(np.linalg.det(A))

-2.0000000000000004


In [ ]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)

[-0.37228132  5.37228132]


In [ ]:
print(eigenvectors)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
C = np.array([5,11])
solution = np.linalg.solve(A, C)
print(solution)

[1. 2.]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
vertical_stack = np.vstack((A,B))
horizontal_stack = np.hstack((A,B))
print(vertical_stack)
print(horizontal_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
split_arr = np.split(np.array([1,2,3,4,5,6]),3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [1]:
!git --version

git version 2.34.1


In [2]:
!git config --global user.name "KrishnaBalaSai"

In [3]:
!git config --global user.email "krishnabalasai123@gmail.com"

In [4]:
!git clone https://github.com/KrishnaBalaSai/Python_Course_Work.git

Cloning into 'Python_Course_Work'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 174 (delta 35), reused 144 (delta 6), pack-reused 0 (from 0)
Receiving objects: 100% (174/174), 201.71 KiB | 3.60 MiB/s, done.
Resolving deltas: 100% (35/35), done.


In [5]:
%cd /content/Python_Course_Work

/content/Python_Course_Work


In [6]:
!ls

Day_1	Day_13	Day_17	Day_20	Day_24	Day_28	Day_31	Day_35	Day_7
Day_10	Day_14	Day_18	Day_21	Day_25	Day_29	Day_32	Day_4	Day_8
Day_11	Day_15	Day_19	Day_22	Day_26	Day_3	Day_33	Day_5	Day_9
Day_12	Day_16	Day_2	Day_23	Day_27	Day_30	Day_34	Day_6


In [7]:
!ls /content

Python_Course_Work  sample_data


In [8]:
!find /content -maxdepth 2 -name "*.ipynb"